-- ============================================================
-- HQ360 — cache column for the Dashboard "AI Welcome" summary.
-- One summary per org per day; regenerated by the dashboard-ai-summary
-- edge function only when stale, so a page reload doesn't re-call Claude.
-- ============================================================

alter table organizations add column ai_summary_text text;
alter table organizations add column ai_summary_date date;
